import type { CSSProperties } from "react";

/** Co-located styles for ConventionCard. */
export const s = {
  card: (muted: boolean): CSSProperties => ({
    padding: 16,
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    opacity: muted ? 0.55 : 1,
  }),
  topRow: { display: "flex", gap: 16, alignItems: "flex-start" } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  metaRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  categoryChip: (color: string): CSSProperties => ({
    fontSize: 12,
    fontWeight: 600,
    color,
  }),
  rule: {
    fontSize: 14.5,
    fontStyle: "italic",
    color: "var(--text-primary)",
    lineHeight: 1.55,
    marginBottom: 12,
  } satisfies CSSProperties,
  evidenceBox: {
    borderRadius: 8,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    overflow: "hidden",
  } satisfies CSSProperties,
  evidenceHead: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "7px 12px",
  } satisfies CSSProperties,
  evidencePath: {
    fontSize: 12,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  githubLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--accent-text)",
    textDecoration: "none",
  } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "0 12px 10px",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    overflowX: "auto",
    whiteSpace: "pre",
    lineHeight: 1.6,
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    flexShrink: 0,
    width: 118,
  } satisfies CSSProperties,
  editActions: { display: "flex", gap: 8, marginTop: 10 } satisfies CSSProperties,
  confidenceRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 14,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  confidenceBar: { width: 140 } satisfies CSSProperties,
} as const;
