import type { CSSProperties } from "react";
import { COLUMN_WIDTH } from "./constants";

/** Co-located styles for AgentColumns. */
export const s = {
  scroller: {
    display: "flex",
    gap: 14,
    overflowX: "auto",
    paddingBottom: 8,
  } satisfies CSSProperties,
  column: (accentColor: string): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    width: COLUMN_WIDTH,
    borderRadius: 8,
    borderStyle: "solid",
    borderTopWidth: 3,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: accentColor,
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: "var(--border)",
    background: "var(--bg-elevated)",
    overflow: "hidden",
  }),
  header: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "12px 14px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  headerTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  } satisfies CSSProperties,
  statusBadge: (color: string, bg: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "2px 8px",
    borderRadius: 5,
    fontSize: 11.5,
    fontWeight: 600,
    color,
    background: bg,
    minWidth: 0,
  }),
  statusLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  name: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  meta: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  body: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 12,
    flex: 1,
  } satisfies CSSProperties,
  errorBox: {
    fontSize: 12.5,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    borderRadius: 6,
    padding: "8px 10px",
    lineHeight: 1.4,
  } satisfies CSSProperties,
  cancelledBox: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    borderRadius: 6,
    padding: "8px 10px",
    lineHeight: 1.4,
  } satisfies CSSProperties,
  findingCard: {
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    padding: "8px 10px",
  } satisfies CSSProperties,
  findingHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
  } satisfies CSSProperties,
  findingTitle: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-primary)",
    lineHeight: 1.4,
  } satisfies CSSProperties,
  findingLocation: {
    fontSize: 11,
    color: "var(--text-muted)",
    marginTop: 4,
  } satisfies CSSProperties,
  findingRationale: {
    fontSize: 11.5,
    color: "var(--text-secondary)",
    marginTop: 4,
    lineHeight: 1.4,
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "10px 14px",
    borderTop: "1px solid var(--border)",
    fontSize: 12,
  } satisfies CSSProperties,
  traceLink: {
    background: "none",
    border: "none",
    padding: 0,
    font: "inherit",
    color: "var(--accent-text)",
    cursor: "pointer",
    textDecoration: "underline",
    textDecorationStyle: "dotted",
    textUnderlineOffset: 3,
  } satisfies CSSProperties,
  findingsCount: {
    color: "var(--text-muted)",
  } satisfies CSSProperties,
} as const;
