import type { CSSProperties } from "react";

/** Co-located styles for CiTab + its `_components`. */
export const s = {
  wrap: { maxWidth: 860, display: "flex", flexDirection: "column", gap: 20 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 16 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-muted)", marginTop: 4 } satisfies CSSProperties,
  headerActions: { display: "flex", alignItems: "center", gap: 10, flexShrink: 0 } satisfies CSSProperties,
  tableCard: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-surface)",
    overflow: "hidden",
  } satisfies CSSProperties,
  headRow: {
    display: "grid",
    gridTemplateColumns: "1fr 140px 140px 110px 100px",
    gap: 8,
    padding: "10px 16px",
    borderBottom: "1px solid var(--border)",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  row: {
    display: "grid",
    gridTemplateColumns: "1fr 140px 140px 110px 100px",
    gap: 8,
    padding: "12px 16px",
    borderBottom: "1px solid var(--border)",
    fontSize: 13,
    alignItems: "center",
  } satisfies CSSProperties,
  loadingStack: { display: "flex", flexDirection: "column", gap: 8, padding: 16 } satisfies CSSProperties,
  repoCell: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  repoName: { fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  staleNote: { fontSize: 12, color: "var(--warn)" } satisfies CSSProperties,
  muted: { color: "var(--text-muted)" } satisfies CSSProperties,
  failOnCard: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  failOnLabel: { fontSize: 14, fontWeight: 700 } satisfies CSSProperties,
  failOnHint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  segmented: { display: "flex", flexWrap: "wrap", gap: 8 } satisfies CSSProperties,
  segmentedOption: (active: boolean): CSSProperties => ({
    padding: "8px 12px",
    borderRadius: 8,
    border: "1px solid " + (active ? "var(--accent)" : "var(--border)"),
    background: active ? "var(--accent-bg)" : "var(--bg-hover)",
    color: active ? "var(--accent-text)" : "var(--text-secondary)",
    fontSize: 12.5,
    fontWeight: 500,
    textAlign: "left",
    lineHeight: 1.4,
    maxWidth: 220,
    cursor: "pointer",
  }),
  branchProtectionNote: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
} as const;
