import type { CSSProperties } from "react";

/** Co-located styles for SkillPreview. */
export const s = {
  page: { padding: "20px 28px 40px", maxWidth: 820 } satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "center", gap: 12, marginBottom: 4 } satisfies CSSProperties,
  iconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: "var(--accent-bg)",
    color: "var(--accent)",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  } satisfies CSSProperties,
  name: { fontSize: 18, fontWeight: 700, flex: 1, minWidth: 0 } satisfies CSSProperties,
  metaRow: { display: "flex", alignItems: "center", gap: 8, margin: "10px 0 18px", flexWrap: "wrap" } satisfies CSSProperties,
  description: { fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.5, marginBottom: 18 } satisfies CSSProperties,
  notice: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "12px 14px",
    borderRadius: 8,
    background: "var(--warn-bg)",
    border: "1px solid var(--warn)",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: 1.5,
    marginBottom: 18,
  } satisfies CSSProperties,
  sectionHeader: { display: "flex", alignItems: "center", marginBottom: 10, gap: 10 } satisfies CSSProperties,
  sectionLabel: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)", flex: 1 } satisfies CSSProperties,
  body: {
    fontSize: 14,
    color: "var(--text-primary)",
    padding: 16,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  editActions: { display: "flex", gap: 8, marginTop: 12 } satisfies CSSProperties,
  tokenCount: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
