import type { CSSProperties } from "react";

/** Co-located styles for AddSkillDrawer. */
export const s = {
  body: { display: "flex", flexDirection: "column" } satisfies CSSProperties,
  footer: { display: "flex", justifyContent: "flex-end", gap: 8 } satisfies CSSProperties,
  dropZone: (over: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "22px 16px",
    borderRadius: 8,
    border: "1.5px dashed " + (over ? "var(--accent)" : "var(--border-strong)"),
    background: over ? "var(--accent-bg)" : "var(--bg-elevated)",
    textAlign: "center",
    transition: "background .1s, border-color .1s",
  }),
  dropHint: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  selectedFileRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
    padding: "8px 10px",
    borderRadius: 6,
    background: "var(--bg-hover)",
    fontSize: 13,
  } satisfies CSSProperties,
  selectedFileName: { flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  divider: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    margin: "18px 0",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  dividerLine: { flex: 1, height: 1, background: "var(--border)" } satisfies CSSProperties,
  errorText: { fontSize: 13, color: "var(--crit)", marginTop: 10 } satisfies CSSProperties,
  previewBody: {
    fontSize: 13,
    padding: 14,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    maxHeight: 320,
    overflow: "auto",
  } satisfies CSSProperties,
  skippedLine: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginTop: 10,
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  placeholder: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    gap: 8,
    padding: "48px 20px",
  } satisfies CSSProperties,
  communityList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginTop: 14,
  } satisfies CSSProperties,
  communityCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  communityCardMain: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 3 } satisfies CSSProperties,
  communityCardTitle: { fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  communityCardMeta: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 11,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  communityCardDesc: {
    fontSize: 12,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
} as const;
