import type { CSSProperties } from "react";

/** Co-located styles for EvalsTab. */
export const s = {
  wrap: { padding: 24, display: "flex", flexDirection: "column", gap: 24 } satisfies CSSProperties,
  tiles: { display: "flex", gap: 14 } satisfies CSSProperties,
  metricsHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: -10,
  } satisfies CSSProperties,
  metricsTitle: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  dashLink: {
    background: "none",
    border: "none",
    padding: 0,
    font: "inherit",
    fontSize: 13,
    color: "var(--accent)",
    cursor: "pointer",
  } satisfies CSSProperties,
  panel: {
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: 18,
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, marginBottom: 12 } satisfies CSSProperties,
  h2: { fontSize: 15, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  caseRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  caseName: { fontFamily: "var(--mono, monospace)", fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  caseMeta: { fontSize: 12, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  caseMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  statusDot: (color: string): CSSProperties => ({
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: color,
    flexShrink: 0,
  }),
  runRow: (selected: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "9px 14px",
    borderRadius: 7,
    border: "1px solid " + (selected ? "var(--accent)" : "var(--border)"),
    background: "var(--bg-elevated)",
    fontSize: 13,
  }),
  runDate: { fontFamily: "var(--mono, monospace)", color: "var(--text-secondary)", width: 130 } satisfies CSSProperties,
  runMetric: (color: string): CSSProperties => ({
    fontFamily: "var(--mono, monospace)",
    color,
    width: 88,
    textAlign: "right",
  }),
  runPassed: { fontWeight: 700, width: 60, textAlign: "right" } satisfies CSSProperties,
  runCost: { color: "var(--text-muted)", width: 64, textAlign: "right", fontFamily: "var(--mono, monospace)" } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  compareGrid: { display: "flex", gap: 12, marginTop: 4 } satisfies CSSProperties,
  compareCell: {
    flex: 1,
    border: "1px solid var(--border)",
    borderRadius: 9,
    padding: 14,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  compareLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  compareValue: { display: "flex", alignItems: "baseline", gap: 8, fontSize: 20, fontWeight: 700 } satisfies CSSProperties,
  compareOld: { color: "var(--text-muted)", fontWeight: 500, fontSize: 15 } satisfies CSSProperties,
  compareDelta: (good: boolean, flat: boolean): CSSProperties => ({
    fontSize: 12,
    fontWeight: 700,
    color: flat ? "var(--text-muted)" : good ? "var(--ok)" : "var(--crit)",
  }),
} as const;
